Bugfix in msCompile ProblemMatcher
The msCompile ProblemMatcher did not match "fatal error" messages (e.g. missing include files), e.g. "foo.cpp(13): fatal error C1083: File (Include) could not be opened". This has been fixed.